"""add_missing_unique_constraints

Revision ID: f6d2b650735e
Revises: a4cd4a58d363
Create Date: 2026-02-22 14:18:04.402314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d2b650735e'
down_revision: Union[str, Sequence[str], None] = 'a4cd4a58d363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_candidate'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.create_unique_constraint('uq_application_job_candidate', 'applications', ['job_id', 'candidate_id'])
    op.drop_index(op.f('ix_assessment_results_candidate_assessment'), table_name='assessment_results')
    op.create_unique_constraint('uq_assessment_result_candidate_assessment', 'assessment_results', ['candidate_id', 'assessment_id'])
    op.drop_index(op.f('ix_assessments_skill_name'), table_name='assessments')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_candidates_user_id'), table_name='candidates')
    op.create_unique_constraint(None, 'candidates', ['user_id'])
    op.drop_index(op.f('ix_conversations_participants'), table_name='conversations')
    op.create_unique_constraint('uq_conversation_participants', 'conversations', ['participant_1', 'participant_2'])
    op.drop_index(op.f('idx_employer_notes_application_id'), table_name='employer_notes')
    op.drop_index(op.f('idx_employer_notes_employer_id'), table_name='employer_notes')
    op.alter_column('employers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_external_jobs_fetched_at'), table_name='external_jobs')
    op.drop_index(op.f('idx_jobs_employer_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employer_status_created'), table_name='jobs')
    op.drop_index(op.f('idx_matches_candidate_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_candidate_score'), table_name='matches')
    op.drop_index(op.f('ix_matches_job_score'), table_name='matches')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('idx_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_candidate_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_candidate_job'), table_name='saved_jobs')
    op.create_unique_constraint('uq_savedjob_candidate_job', 'saved_jobs', ['candidate_id', 'job_id'])
    op.drop_index(op.f('idx_subscriptions_employer_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('idx_usage_counters_employer_id'), table_name='usage_counters')
    op.drop_index(op.f('ix_usage_employer_month'), table_name='usage_counters')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_usage_employer_month'), 'usage_counters', ['employer_id', 'month'], unique=True)
    op.create_index(op.f('idx_usage_counters_employer_id'), 'usage_counters', ['employer_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_employer_id'), 'subscriptions', ['employer_id'], unique=False)
    op.drop_constraint('uq_savedjob_candidate_job', 'saved_jobs', type_='unique')
    op.create_index(op.f('ix_saved_jobs_candidate_job'), 'saved_jobs', ['candidate_id', 'job_id'], unique=True)
    op.create_index(op.f('ix_saved_jobs_candidate_id'), 'saved_jobs', ['candidate_id'], unique=False)
    op.create_index(op.f('idx_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_matches_job_score'), 'matches', ['job_id', 'score'], unique=False)
    op.create_index(op.f('ix_matches_candidate_score'), 'matches', ['candidate_id', 'score'], unique=False)
    op.create_index(op.f('idx_matches_candidate_id'), 'matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_jobs_employer_status_created'), 'jobs', ['employer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_jobs_employer_id'), 'jobs', ['employer_id'], unique=False)
    op.create_index(op.f('idx_external_jobs_fetched_at'), 'external_jobs', ['fetched_at'], unique=False)
    op.alter_column('employers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_employer_notes_employer_id'), 'employer_notes', ['employer_id'], unique=False)
    op.create_index(op.f('idx_employer_notes_application_id'), 'employer_notes', ['application_id'], unique=False)
    op.drop_constraint('uq_conversation_participants', 'conversations', type_='unique')
    op.create_index(op.f('ix_conversations_participants'), 'conversations', ['participant_1', 'participant_2'], unique=True)
    op.drop_constraint(None, 'candidates', type_='unique')
    op.create_index(op.f('idx_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_assessments_skill_name'), 'assessments', ['skill_name'], unique=False)
    op.drop_constraint('uq_assessment_result_candidate_assessment', 'assessment_results', type_='unique')
    op.create_index(op.f('ix_assessment_results_candidate_assessment'), 'assessment_results', ['candidate_id', 'assessment_id'], unique=True)
    op.drop_constraint('uq_application_job_candidate', 'applications', type_='unique')
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_job_candidate'), 'applications', ['job_id', 'candidate_id'], unique=True)
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
